name:                pl2303rfid
version:             0.1.0.0
# description:
homepage:            https://github.com/renesat/pl2303
license:             MIT
author:              Smolyakov Ivan
maintainer:          smol.ivan97@gmail.com
copyright:           2021 Smolyakov Ivan
category:            Hardware

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - serialport
  - bytestring
  - hex
  - attoparsec == 0.13.*
  - optparse-applicative == 0.16.*
  - exceptions


ghc-options: -Wall

library:
  source-dirs:      src

executables:
  pl2303rfid:
    main: Main.hs
    source-dirs: app/
    dependencies:
      pl2303rfid
